services:
  app:
    build: .
    container_name: prova
    working_dir: /app
    volumes:
      - .:/app               # volume vinculado ao diret√≥rio local
      - /app/node_modules    # evita conflito com node_modules local
    ports:
      - "3311:3000"
    environment:
      - NODE_ENV=development